# Comm prefix FATECLOUD
registry: "federatedai"
tag: "1.2.0-release"
partyList:
  - partyId: 10000
    nodePort: 30010
    namespace: fate-10000
  - partyId: 9999
    nodePort: 30009
    namespace: fate-9999

server:
  address: localhost
  port: 8080

mongo:
  url: localhost:27017
  username: root
  password: root
  database: KubeFate

log:
  level: debug

chart:
  repository: "https://example.com/charts/" # chart url https://example.com/charts/fate-1.2.0.tgz

# TODO
# persistent layer
