# Comm prefix FATECLOUD

server:
  address: localhost
  port: 8080

mongo:
  url: 10.184.97.99:27017
  username: root
  password: root
  database: KubeFate

log:
  level: debug

chart:
  repository: "https://owlet42.github.io/helm-chart/" # chart url https://example.com/charts/fate-1.2.0.tgz

# TODO
# persistent layer

user:
  username: admin
  password: admin