apiVersion: v1
kind: Namespace
metadata:
  name: kubefate
  labels:
    name: kubefate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefate
  namespace: kubefate
  labels:
    fate: kubefate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fate: kubefate
  template:
    metadata:
      labels:
        fate: kubefate
    spec:
      containers:
        - image: slelove/kubefate
          imagePullPolicy: IfNotPresent
          name: kubefate
          env:
            - name: FATECLOUD_MONGO_URL
              value: "127.0.0.1:27017"
          ports:
            - containerPort: 8080
        - image: mongo
          imagePullPolicy: IfNotPresent
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 27017
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kubefate
  namespace: kubefate
  labels:
    fate: kubefate
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    fate: kubefate