apiVersion: v1
kind: Namespace
metadata:
  name: kubefate
  labels:
    name: kubefate
---
piVersion: v1
kind: ServiceAccount
metadata:
  name: kubefate-admin
  namespace: kubefate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubefate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubefate-admin
    namespace: kubefate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefate
  namespace: kubefate
  labels:
    fate: kubefate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fate: kubefate
  template:
    metadata:
      labels:
        fate: kubefate
    spec:
      serviceAccount: kubefate-admin
      containers:
        - image: slelove/kubefate
          imagePullPolicy: Always
          name: kubefate
          env:
            - name: FATECLOUD_MONGO_URL
              value: "mongo:27017"
            - name: FATECLOUD_REPO_NAME
              value: "kubefate"
            - name: FATECLOUD_REPO_URL
              value: "https://owlet42.github.io/helm-chart/"
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: kubefate
  labels:
    fate: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fate: mongo
  template:
    metadata:
      labels:
        fate: mongo
    spec:
      containers:
        - image: mongo
          imagePullPolicy: IfNotPresent
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 27017
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: kubefate
  labels:
    fate: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
  selector:
    fate: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: kubefate
  namespace: kubefate
  labels:
    fate: kubefate
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    fate: kubefate
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubefate
  namespace: kubefate
  annotations:
spec:
  rules:
    - host: kubefate.net
      http:
        paths:
          - path: /
            backend:
              serviceName: kubefate
              servicePort: 8080