apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefate
  labels:
    fate: kubefate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fate: kubefate
  template:
    metadata:
      labels:
        fate: kubefate
    spec:
      containers:
        - image: federatedai/kubefate
          imagePullPolicy: IfNotPresent
          name: kubefate
          env:
            - name: FATECLOUD_USER_USERNAME
              value: admin
            - name: FATECLOUD_USER_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data/projects/fatecloud/
              subPath: helmchart
              name: helmchart-path
        - image: mongo
          imagePullPolicy: IfNotPresent
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 27017
      restartPolicy: Always
      volumes:
        - name: helmchart-path
          hostPath:
            path: /data/projects/fatecloud/helmchart
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: kubefate
  labels:
    fate: kubefate
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    fate: kubefate